modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mcdevmod"
version = "${version}"
displayName = "McDevMod"
authors = "Paspartout"
description = '''
Mod that contains various utilities to help mod development.
'''
#logoFile = ""

[[dependencies.mcdevmod]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcdevmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"